[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
openshelf = "4ndujP9V3z319gyw1rYSvqjjzc71UXUZgd42L9GjHe1d"

[programs.devnet]
openshelf = "4ndujP9V3z319gyw1rYSvqjjzc71UXUZgd42L9GjHe1d"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
