[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
openshelf = "7LPXnLBKNzpwhqfwfeaXVK4airqY5r3n2L4kabfZPAms"

[programs.localnet]
openshelf = "7LPXnLBKNzpwhqfwfeaXVK4airqY5r3n2L4kabfZPAms"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
