[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
openshelf = "JmuTfDL4F9Fo8DfsTFh3gr7VguiX7euz9vwnddoQrUh"

[programs.localnet]
openshelf = "JmuTfDL4F9Fo8DfsTFh3gr7VguiX7euz9vwnddoQrUh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
