[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
openshelf = "GfNgYXDz7Vn51iBiyb8781Adgw4GcnceAWViuDj1zC89"

[programs.localnet]
openshelf = "GfNgYXDz7Vn51iBiyb8781Adgw4GcnceAWViuDj1zC89"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/index.ts"
